name = free_miners
description = Spawns a player-like Miner NPC that mines a 14x14x7 area and deposits items into chests.
author = ronrob-lu
optional_depends = default, mcl_core, mcl_chests, mcl_tools
